### PR TITLE
geoBottomley v4

### PR DESCRIPTION
**Pull request by Fil**
claiming bottomley for #32

I agree with https://github.com/d3/d3-geo-projection/pull/34#issuecomment-229707919 , and apply the principle of least effort to dispense with numerical tests.

I'm not too sure about the parameter thing: how to present it, how to use it (is this something to document in the section about "raw" projections?)

### CODE REVIEW

**Comment by mbostock** [comment]
Document the custom projection methods like this:

```md
<a href="#bottomley_psi" name="bottomley_psi">#</a> <i>bottomley</i>.<b>psi</b>([<i>psi</i>])

If *psi* is specified, blah blah blah…
```

See [*berghaus*.lobes](https://github.com/d3/d3-geo-projection/tree/4#berghaus_lobes) for an example.

**Comment by mbostock** [comment]
Oh, my mistake, that parameter isn’t currently configurable on the projection. Though it sounds like it should be.

Please remember to also add the raw projection to the README when you update it. Thanks!

**Comment by mbostock** [comment]
I checked and in 3.x this was exposed as *bottomley*.variant, which set ψ. However, in the paper it seems like it’s more convenient to set sin(ψ) in [0,1], so I did that, and renamed it to *bottomley*.fraction.

**Comment by Fil** [comment]
Thank you, much appreciated. I use this projection as an exercise and a
test bed, so it's very good to see the whole coverage.

**Pull request merged**
