### PR TITLE
port polyhedron projections to v4

### PR DESCRIPTION
**Pull request by Fil**
Ref: https://github.com/d3/d3-geo/issues/47

### CODE REVIEW

**Comment by Fil** [comment]
The results at this point:

polyhedronbutterfly

polyhedronwaterman

**Comment by Fil** [comment]
Comment from https://github.com/d3/d3-geo-projection/pull/69/commits/27f28200299385a06c58178d2a5999a4454a609e : I couldn't run `test/compute-scale` on the polyhedronButterfly because the computation of the land bounds yields `[ -4.440892098500626e-16, -1.2247448713915885 ]`. This tiny negative x has no inverse. I've computed the scale with x=0 instead.

**Comment by Fil** [comment]
It's ready to review.

`npm run pretest && test/render-world polyhedronButterfly && test/render-world polyhedronCollignon && test/render-world polyhedronWaterman`

A few problems:

1) `test/compute-scale` fails on these three projections:
- I had to tweak it to get the correct `scale()` for waterman and butterfly (see https://github.com/d3/d3-geo-projection/pull/69#issuecomment-239605274)
- the scale was ok for the collignon, but I had to find the `center()` by hand and eye

2)  To adapt the collignon projection to equilateral triangles, I needed to multiply the resulting `x` by some factor (`2/sqrt(3)`). I did this by adding a projection mutator to collignon.js and it works, but it seems obvious to me that it is not the right method. What I would like is a generic method to compose two projections, so I could write `collignonrescaled = compose (collignon, rescale)` and get everything in order. It would be useful for many other things.  (It could be written `collignonrescaled = collignon.compose(rescale)` ).

3) I'm not too sure about the names and exports

4) I need to write the docs and add the reference images to img/

**Comment by Fil** [comment]
## butterfly
polyhedronbutterfly

## collignon
polyhedroncollignon

## waterman
polyhedronwaterman

**Comment by mbostock** [comment]
collignonRaw is an exported symbol so this change would not be backwards-compatible. Given the simplicity of what you are trying to do, I would just create a local raw projection that wraps collignonRaw and its invert multiplying by the appropriate scale factor for x. (No need to bother with fancy function composition either, since that just adds overhead.)

**Comment by Fil** [comment]
All set. Do you think polyhedronButterfly should be named polyhedronGnomonic?

**Comment by Fil** [comment]
We probably have to write somewhere that the Waterman butterfly projection is not complete yet (it doesn't isolate the South Pole), or just open another issue for this.

**Comment by mbostock** [comment]
I restructured the code into separate files and merged to master. Thanks, and thank you to Jason Davies for the original implementation!

**Pull request merged**
