### PR TITLE
geoWinkel3

### PR DESCRIPTION
**Pull request by Fil**
claiming winkel3 for https://github.com/d3/d3-geo-projection/issues/32

- [x] projection
- [x] tests
- [ ] all tests passing
- [x] image (optimized)
- [x] add image to the README

### CODE REVIEW

**Comment by Fil** [comment]
One of the tests fails:

```
not ok 171 should be in delta 0.000001
  ---
    operator: inDelta
    expected: |-
      [ 179.99999954219686, 0 ]
    actual: |-
      [ -180, 0 ]
    at: Test.tape.Test.inDelta (/Users/fil/Sites/d3/d3-geo-projection-pr/test/inDelta.js:5:8)
  ...
```

My take would be that 179.99999954219686 is within delta of -180 and should pass.

**Comment by mbostock** [comment]
Yes.

**Comment by Fil** [comment]
We don't want to have special cases everywhere. This could to be change in
inDelta, or a specialized function. I'd be more comfortable if you decided
on the correct method. Then I could port all the remaining tests in one
swoop.

**Comment by Fil** [comment]
Another question re this PR, I am not happy with the fact that I have uploaded the whole `src/winkel3.js` as a "new" file, thus losing the history. I should have commited a "copy from master" first. Is this not something that could also be done in one swoop?

**Comment by mbostock** [comment]
I am going to squash this branch in the merge so the history should be
preserved before it becomes master.

**Comment by mbostock** [comment]
I replace inDelta with sphericalEqual.

I’m going to reformat the winkel3 test to match the other tests. I know there’s a bit of duplication there but I’d rather have the tests consistent.

It’s possible we should do away with the point-based tests entirely, too, since they are relatively useless now that we have the image-based testing.

**Pull request merged**
