### PR TITLE
Robinson: remove unnecessary halfPi, use sign

### PR DESCRIPTION
**Pull request by mrhso**

### CODE REVIEW

**Review by Fil — CHANGES_REQUESTED** [review]
I'm surprised by the value
1.5933781076941205 
since
1.593415793900743 = 1.0144 * Math.PI / 2

**Comment by mrhso** [comment]
> I'm surprised by the value
> 1.5933781076941205
> since
> 1.593415793900743 = 1.0144 * Math.PI / 2

According to the original algorithm of Robinson projection:
x = 0.8487RXλ
y = 1.3523RY

The scale factor should be 1.3523 / 0.8487.
(1.3523 / 0.8487) / (π / 2) ≐ 1.0144

**Comment by Fil** [comment]
The difference between the two constants is 0.002%, smaller than the precision of the numbers in the original description, but enough to make the regression test fail. So if we wanted to change that, we'd need to justify it in some way, probably because we'd want to follow the original definition, or a standard.

In other words, my question should have been: is this PR about the simplification of the code (in which case the constant should be 1.593415793900743, and the projection unchanged). Or is it _also_ about enforcing a (very slightly) different aspect ratio (in which case the constant could be written explicitly as 1.3523 / 0.8487, and the reference image updated).

I don't have access to the original Robinson paper (1974) to double check, but [Snyder 1990](https://sci-hub.se/https://www.tandfonline.com/doi/10.1559/152304090783805654) (who gives a fortran program with 1.3523, 0.8487 and 0.5072 (ie 1.0144/2)), quotes from it:
> "The length of the equator of the projection is 0.8487 times the circumference of a sphere of equal area, and the length of
the central meridian of the projection is 0.5072 times the length of the equator of the projection" (Robinson
1974, 151)

In my understanding, this means that the current code already follows Robinson's original formulation (the aspect ratio is 1:0.5072), and our constant should be defined as 0.5072 * π (at our precision, 1.593415793900743). 1.3523 is just an approximation to 1e-5 derived by Snyder, and not part of the original formulation; it should be 0.8487 * 0.5072 * π = 1.35233…

**Comment by mrhso** [comment]
Changed.

**Comment by Fil** [comment]
thanks!

**Pull request merged**
