### PR TITLE
Map in a cube

### PR DESCRIPTION
**Pull request by espinielli**
I am trying to add another polyhedral map projection.
I took inspiration from [Furuti's Cubic Globes](http://www.progonos.com/furuti/MapProj/Normal/ProjPoly/projPoly2.html).

I extended `render-world` accordingly and I get the following "piece of art" ;-)
polyhedralreichard

If I take away the clipping part in `render-world` I see this other _mess_:
polyhedralreichard

So things seems to be somewhat in place but maybe clipping needs special treatment...
Any helps?

### CODE REVIEW

**Comment by espinielli** [comment]
It looks like the clip to an arbitrary spherical polygon is needed by other (requested) map projections, #67 , #25.
Out of curiosity, what did prevent Jason from contributing it to D3? Was the implementation not generic enough?

I think Jason outlined some issues and possible solutions in [Geographic Clipping/Spherical Polygon Challenges](https://www.jasondavies.com/maps/clip/).

PS: Speaking of the [great circle arc intersection](https://www.jasondavies.com/maps/intersect/) you mentioned, I did write [a post](http://enrico.spinielli.net/understanding-great-circle-arcs_57/) to document my search of the "rationale" for the algorithm used by Jason (and exchange some emails w/ him).
By the way, I miss the point about you mentioning "great circle arc intersection" in this thread/PR...

**Comment by espinielli** [comment]
Is [this code](https://gitlab.com/rrmodi88/d3/commit/8de355d1b50ba08b625164d0f64bdc85dc7e2759#50c8d58b7e0c6bd18ca8e68f8461eec4103defcb) a D3's implementation? It looks like an old implementation...?

**Comment by mbostock** [comment]
That code looks like an old version of [src/clip/polygon.js](https://github.com/d3/d3-geo/blob/master/src/clip/polygon.js). D3 can clip spherical polygons to a great circle or to the antimeridian, but it cannot clip spherical polygons to another spherical polygon. If you want to implement the equivalent of [Weiler–Atherton clipping](https://en.wikipedia.org/wiki/Weiler–Atherton_clipping_algorithm) on the sphere then you’re going to need to be able to compute the intersection of geodesics, which is why I mentioned it.

**Comment by espinielli** [comment]
From the code of Cahill-Keys (including `polyhedron.js` from Jason) I got a working [Earth in a Cube](http://bl.ocks.org/espinielli/1018c88657010f8ee93ea4224652e3cf).

screen shot 2017-01-15 at 10 26 50 pm

It is a D3v3 version but it shows that `polyhedron.js` contains enough ingredients to make things work.
Again that code was from @jasondavies ...I do not know under which license it can be used/ported to D3v4 or if I should even take it away from my blocks...

**Comment by mbostock** [comment]
v4 supports polyhedral projections:

https://github.com/d3/d3-geo-projection/blob/master/README.md#polyhedral-projections
https://github.com/d3/d3-geo-projection/blob/master/src/polyhedral/index.js

Can you implementing it using the v4 API?

**Comment by espinielli** [comment]
Not possible. The modified D3v3 version from Jason had a d3.geo.pointInPolygon(point, polygon) which is not in D3v4.

**Comment by mbostock** [comment]
Isn’t that the [polygonContains](https://github.com/d3/d3-geo/blob/master/src/polygonContains.js) function? I’d be fine exposing that as d3.geoPolygonContains.

**Comment by mbostock** [comment]
Though that one requires the input coordinates are in radians, and it’d probably be worth generalizing it to d3.**geoContains**(*feature*, *point*), where *feature* is any GeoJSON feature (in degrees).

**Comment by espinielli** [comment]
I tried by just generating a version of `d3.geo` that exposes `polygonContains`.
Using all v4 libraries I get a map without proper clipping:

screen shot 2017-01-17 at 12 00 47 pm

So clipping spherical polygons is really needed...

**Comment by Fil** [comment]
very cute :)

on geoPolygonContains, see also https://github.com/d3/d3/issues/2662#issuecomment-245274426

**Comment by espinielli** [comment]
@Fil yes I saw it...but wanted to try the simple things first...not sure I am able to follow up on @mbostock's suggestion.
BTW [`polygonContains`](https://github.com/d3/d3-geo/blob/master/src/polygonContains.js) takes coordinates in degrees, see [the relevant tests](https://github.com/d3/d3-geo/blob/master/test/polygon-contains-test.js).

**Comment by mbostock** [comment]
So if an equivalent to d3.geo.pointInPolygon is available as d3.geoContains (or the internal polygonContains), what API is missing to make this work in v4? Or is it that the replacement for pointInPolygon is not working correctly?

**Comment by mbostock** [comment]
I have opened a feature request for d3.geoContains, d3/d3-geo#73, since that has come up twice now and seems like an obvious win.

**Comment by espinielli** [comment]
What I noticed is different is the implementation of [`recurse`](https://github.com/d3/d3-geo-projection/blob/master/src/polyhedral/index.js#L21) in `polyhedral.js` compared to the one in [`polyhedron.js`](http://bl.ocks.org/espinielli/1018c88657010f8ee93ea4224652e3cf#d3.geo.polyhedron.js).

The latter does something with `ring`...

**Comment by Fil** [comment]
Hey I have put a lot of effort into this and I have to report I'm stuck at about the same point as @espinielli  😿

For fun I chose the third map in the Furuti page. Building the cube and faces is OK, and much simpler now that we have geoContains.
https://gist.github.com/Fil/49fc5cd4c6ba54465e23c2c6544ff1d3

However, I wasn't able to find how to avoid lines going straight from one face to the other (which is utterly disastrous when it's not going through a shared edge).

Here's what it gives with render-world.
f3

I suppose the answer is some kind of polygon clipping to the set of faces, as Enrico demonstrated in his d3v3 version, but it escapes me how to implement it :(

(After all this time I've spent in d3-geo, I must say its code and operation are still sometimes quite difficult to grasp.)

**Comment by mbostock** [comment]
Have you looked at Jason’s implementation of clipping to an arbitrary spherical polygon? It’s in the [clip-polygon branch of d3](https://github.com/d3/d3/commits/clip-polygon). It’s four years old and the code has since moved to d3-geo, and as you say the code can be difficult to follow, but it might be helpful in understanding what is necessary.

**Comment by Fil** [comment]
I've spent a few more hours on this, now I think I'm beginning to understand a few more things, but still no success. The first step would be to expose the old clipPolygon in d3-geo in a way that would allow to use `projection.clipPolygon([polygon])`.

But all the names have been changed, it's a strange maze.

If I summarize we now have:

- d3_geo_clip   =>  exposed as clip
- d3_geo_clipPolygonRejoin => exposed as clipPolygon

- d3_geo_clipPolygon => unported (hard); it needs d3_geo_clipPolygonSort d3_geo_clipPolygonDistance and more ; would have to be renamed as clipPolygonSet or something 
- projection.clipPolygon =>  unported (relatively easy)

I've begun some babbling here
https://gist.github.com/Fil/dd1383ddd8669c8c1b97d5ca5dce1035

good night

**Comment by mbostock** [comment]
If it helps, here’s [a compare view for those two commits](https://github.com/d3/d3/compare/clip-polygon~2...clip-polygon). The main new things are:

* [src/geo/clip-polygon.js](https://github.com/d3/d3/blob/clip-polygon/src/geo/clip-polygon.js) - to clip spherical geometry to an arbitrary spherical polygon.
* [src/geo/intersect.js](https://github.com/d3/d3/blob/clip-polygon/src/geo/intersect.js) - to compute the intersection of two geodesics (spherical line segments); used by src/geo/clip-polygon.js.

v4’s [src/clip/polygon.js](https://github.com/d3/d3-geo/blob/v1.6.1/src/clip/polygon.js) corresponds to the clip-polygon branch’s [src/geo/clip-polygon-rejoin.js](https://github.com/d3/d3/blob/clip-polygon/src/geo/clip-polygon-rejoin.js). A bunch of stuff was renamed in the great port to ES modules, but you can see that the two still have similar structure.

One confusion is that in v4 the “polygon” refers to *what* is being clipped, whereas in the clip-polygon branch the “polygon” refers to *how* the geometry is clipped. That is, in v4 it’s an abstract algorithm for clipping polygons which is used to implement both [circle](https://github.com/d3/d3-geo/blob/v1.6.1/src/clip/circle.js) and [antimeridian](https://github.com/d3/d3-geo/blob/v1.6.1/src/clip/antimeridian.js) clipping, whereas in clip-polygon it’s an implementation for clipping spherical geometry to an arbitrary spherical polygon.

**Comment by mbostock** [comment]
One of the difficulties in understand this code is moving between the concrete (e.g., ) and abstract clipping algorithms. I wonder whether things could be simplified, at the cost of some code duplication, by foregoing any generalized abstract clipping algorithm, and just having separate implementations for clipping to the antimeridian or circle (or spherical polygon). That is, a more compositional approach rather than trying to subclass an abstract implementation.

**Comment by mbostock** [comment]
Related to the preceding comment, one of the changes Jason made was to require an intersection sorting function be passed to the abstract clipping algorithm: the one in v4 uses a sorting function that [only works](https://github.com/d3/d3-geo/blob/v1.6.1/src/clip/index.js#L130-L131) for circle or antimeridian clipping.

**Comment by Fil** [comment]
I've made a block to help visualise the type of polygons we're dealing with.
https://bl.ocks.org/Fil/694ba0d0bc1fc4c24eb257dc210eb01a
capture d ecran 2017-03-08 10 24 03

PS: maybe it would be necessary to open a new issue for this, in d3-geo?

**Comment by mbostock** [comment]
There’s already an issue for clipping to an arbitrary spherical polygon, d3/d3-geo#46. I think that’s the primary blocking feature for more polyhedral projections.

**Comment by Fil** [comment]
I've managed to incorporate Jason Davies' old clip-polygon branch into d3v4, and it sort-of works in some cases.


more later…

**Comment by espinielli** [comment]
This opens the flood's gates!

**Comment by Fil** [comment]
Pull-request for clip-polygon opened at https://github.com/d3/d3-geo/pull/108.

For this projection and others of the [Furuti collection](http://www.progonos.com/furuti/MapProj/Normal/ProjPoly/projPoly2.html), let's maybe create a family rather than create them one by one?

**Comment by Fil** [comment]
Closing this in favor of #129  — will be solved after d3-geo/clip (https://github.com/d3/d3-geo/pull/115) is merged and published to npm.

**Pull request closed without merging**
