### PR TITLE
Equal Earth projection

### PR DESCRIPTION
**Pull request by Fil**
https://github.com/d3/d3-geo-projection/issues/138

### CODE REVIEW

**Comment by mbostock** [comment]
I feel like this is useful enough to include directly in d3-geo rather than d3-geo-projection.

**Comment by Fil** [comment]
Can do. But it's visually *very* similar to [geoNaturalEarth1](https://github.com/d3/d3-geo#geoNaturalEarth1) so I'm not sure it brings that much value. Maybe a good way to slowly deprecate geoNaturalEarth1 from d3-geo though :)

**Comment by mbostock** [comment]
Yeah, my thought is that this is a better replacement for geoNaturalEarth1 (since it’s equal-area).

**Comment by Fil** [comment]
superceded by https://github.com/d3/d3-geo/pull/144

**Pull request closed without merging**
